name: API Diff Report

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  stageProgress: "progress"
  stageEnd: "end"
  prApiOutput: "~/pr_branch"
  baseApiOutput: "~/base_branch"
  diffReportOutput: "~/diff_report"

jobs:
  diff_report:
    if: github.event.pull_request.base.ref == 'master'
    runs-on: macos-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Copy diff report tools
        run: cp -a scripts/api_diff_report/. ~/api_diff_report

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install Prerequisites
        run:  ~/api_diff_report/prerequisite.sh

      - name: Clean Diff Report Comment in PR
        run: |
          python ~/api_diff_report/pr_commenter.py --stage ${{ env.stageProgress }} \
            --token ${{github.token}} \
            --pr_number ${{github.event.pull_request.number}} \
            --commit $GITHUB_SHA \
            --run_id ${{github.run_id}}

      - id: get_changed_files
        name: Get changed file list
        run: echo "file_list=$(git diff --name-only -r HEAD^1 HEAD | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Generate API files for PR branch
        run: python ~/api_diff_report/api_info.py -f ${{ steps.get_changed_files.outputs.file_list }} -o ${{ env.prApiOutput }} -t "~/api_diff_report/theme"

      - name: Checkout Base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Generate API files for Base branch
        run: python ~/api_diff_report/api_info.py -f ${{ steps.get_changed_files.outputs.file_list }} -o ${{ env.baseApiOutput }} -t "~/api_diff_report/theme"

      - name: Generate API Diff Report
        run: python ~/api_diff_report/api_diff_report.py -p ${{ env.prApiOutput }} -b ${{ env.baseApiOutput }} -o ${{ env.diffReportOutput }}

      - name: Update Diff Report Comment in PR
        run: |
          python ~/api_diff_report/pr_commenter.py --stage ${{ env.stageEnd }} \
            --report ${{ env.diffReportOutput }} \
            --token ${{github.token}} \
            --pr_number ${{github.event.pull_request.number}} \
            --commit $GITHUB_SHA \
            --run_id ${{github.run_id}}

      - uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: api_info
          path: | 
            ${{ env.prApiOutput }}
            ${{ env.baseApiOutput }}
            ${{ env.diffReportOutput }}
          retention-days: 1
