name: API Diff Report

on: [pull_request]

jobs:
  diff_report:
    runs-on: macos-latest

    steps:
      - name: Install Sourcekitten
        run:  brew install sourcekitten

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changes
        run: git diff --name-only -r HEAD^1 HEAD

      - name: Make diff directory
        run: mkdir ~/diff

      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
