name: API Diff Report

on: [pull_request]

jobs:
  diff_report:
    runs-on: macos-latest

    steps:
      - name: Install Sourcekitten
        run:  brew install sourcekitten

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: get_changed_files
        run: echo "file_list=$(git diff --name-only -r HEAD^1 HEAD | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Generate API files for PR branch
        run: python scripts/api_diff_report/api_info.py -f ${{ steps.get_changed_files.outputs.file_list }}

      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
